# Generated by Django 5.0.6 on 2024-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_productpricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="apply_on_all",
            field=models.BooleanField(default=False),
        ),
    ]
