# Generated by Django 5.0.6 on 2024-06-17 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_discountcode_apply_on_all"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="depth",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
